# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('receipt', models.TextField(max_length=1000)),
                ('extra_param', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
